### PR TITLE
Send coverage to Coveralls

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Done. https://coveralls.io/github/thepinecode/bazar

Please squash my commits.

**Comment by szepeviktor** [comment]
Maybe we should use the native badge

```markdown
[![Coverage Status](https://coveralls.io/repos/github/thepinecode/bazar/badge.svg?branch=master)](https://coveralls.io/github/thepinecode/bazar?branch=master)
```

**Comment by iamgergo** [comment]
Do I need to configure the github repo?
`COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

**Comment by szepeviktor** [comment]
> Do I need to configure the github repo?

NO!
GitHub Actions automatically populates a token per each run.
https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret

**Pull request merged**
