### PR TITLE
Ugly fix for laravel in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
# 👺

### CODE REVIEW

**Comment by szepeviktor** [comment]
@iamgergo All 🍏

**Comment by iamgergo** [comment]
Let's wait for the PR if it gets merged, I think it will be as patch so will release today.

**Comment by szepeviktor** [comment]
Okay.

**Comment by szepeviktor** [comment]
Dream come true! 🎉 

https://github.com/laravel/framework/pull/34245#event-3750795901

**Pull request closed without merging**
