### PR TITLE
Remove else from TaxRepository

### PR DESCRIPTION
**Pull request by szepeviktor**
Else is not our friend.

# 🤼‍♂️

### CODE REVIEW

**Comment by iamgergo** [comment]
DiscountRepository has the same format, we might update that as well.

**Comment by szepeviktor** [comment]
Done.

**Comment by szepeviktor** [comment]
With many **FREE** empty lines :)

**Comment by iamgergo** [comment]
Thanks!

**Comment by szepeviktor** [comment]
BTW There are anti-dot-operator (and anti-developer) tools :) https://github.com/szepeviktor/phpcs-psr-12-neutron-hybrid-ruleset/blob/a76b66efd2b10212e4d2ab8b76a9380f590648ff/PSR12NeutronRuleset/Sniffs/Strings/ConcatenationUsageSniff.php#L20-L41

Maybe I develop an anti-else laser gun 🔫

**Pull request merged**
